version: "3.3"

services:
  postgres-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store 
      - POSTGRES_USER=gadgeter
      - POSTGRES_PASSWORD=password
    ports: [5432:5432] 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:5
    environment:
    - MYSQL_DATABASE=my_store 
    - MYSQL_USER=gadgeter
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_PORT=3306
    ports: [3306:3306] 
    volumes:
      - ./mysql_data:/var/lib/mysql